// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZ6seGuKiQ-WAUWDf87-CSjgH1TVKAKo',
    appId: '1:155870906905:web:0092b442b7567195787888',
    messagingSenderId: '155870906905',
    projectId: 'final-232fc',
    authDomain: 'final-232fc.firebaseapp.com',
    storageBucket: 'final-232fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3DZGR1cilFprEhK8rrx59a435TtJEyc',
    appId: '1:155870906905:ios:43a7d9d907cb687f787888',
    messagingSenderId: '155870906905',
    projectId: 'final-232fc',
    storageBucket: 'final-232fc.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3DZGR1cilFprEhK8rrx59a435TtJEyc',
    appId: '1:155870906905:ios:43a7d9d907cb687f787888',
    messagingSenderId: '155870906905',
    projectId: 'final-232fc',
    storageBucket: 'final-232fc.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgZ6seGuKiQ-WAUWDf87-CSjgH1TVKAKo',
    appId: '1:155870906905:web:dfc993a35953cff1787888',
    messagingSenderId: '155870906905',
    projectId: 'final-232fc',
    authDomain: 'final-232fc.firebaseapp.com',
    storageBucket: 'final-232fc.firebasestorage.app',
  );
}
